config/routes.rb
Rails.application.routes.draw do
  root "calendar#index"
  get "/calendar", to: "calendar#index"

  get "/training", to: "training#list_dates", as: "training_dates"
  get "/training/:date", to: "training#list_times", as: "training_times"
  get "/training/:date/:time", to: "training#details", as: "training_details"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
  end
end

app/controllers/training_controller.rb
require "#{File.dirname(__FILE__)}/../../lib/polar/lib/polar_data_parser"

class TrainingController < ApplicationController
  def get_directory()
    return "#{File.dirname(__FILE__)}/../../synch/U/0"
  end

  def get_date_directory(date)
    return "#{self.get_directory()}/#{date}/E"
  end

  def get_time_directory(date, time)
    return "#{self.get_date_directory(date)}/#{time}"
  end

  def is_valid_date(date)
    return /^\d{8}$/ =~ date
  end

  def is_valid_time(time)
    return /^\d{6}$/ =~ time
  end

  def list_dates
    directory = self.get_directory()
    if !Dir.exists?(directory)
      render status: :not_found
      return false
    end

    entries = Dir.entries(directory)
    @dates = entries.select {|entry| self.is_valid_date(entry) }.sort
  end

  def list_times
    @date = params[:date]

    directory = self.get_date_directory(@date)
    if !Dir.exists?(directory)
      render status: :not_found
      return false
    end

    entries = Dir.entries(directory)
    @times = entries.select {|entry| self.is_valid_time(entry) }.sort
  end

  def details
    @date = params[:date]
    time = params[:time]

    date_is_valid = /^\d{8}$/ =~ @date
    time_is_valid = /^\d{6}$/ =~ time

    if !date_is_valid || !time_is_valid
      render status: :bad_request
      return false
    end

    directory = self.get_time_directory(@date, time)

    if !Dir.exists?(directory)
      render status: :not_found
      return false
    end

    parsed = PolarDataParser.parse_training_session(directory)

    @sport = parsed[:sport]
    @training_session = parsed[:training_session]
    @sensors = parsed[:sensors]
    @samples = parsed[:samples]
    @route_samples = parsed[:route_samples]
    @swimming_samples = parsed[:swimming_samples]
    @laps = parsed[:exercise_laps]
    @exercise_stats = parsed[:exercise_stats]

    recording_interval = @samples.recording_interval.hours * 3600 + @samples.recording_interval.minutes * 60 + @samples.recording_interval.seconds + (@samples.recording_interval.millis.to_f / 1000)
    samples_count = @samples.speed_samples.count
    chart_data = Array.new
    timestamp = Time.at(0).utc
    for i in 0..samples_count-1
      timestamp += recording_interval

      heart_rate = 0
      distance = 0
      pace = 0

      if @samples.heart_rate_samples[i]
        heart_rate = @samples.heart_rate_samples[i]
      end
      if @samples.distance_samples[i]
        distance = "%7.1f" % @samples.distance_samples[i]
      end
      if @samples.speed_samples[i]
        if @samples.speed_samples[i] > 0
          pace = @samples.speed_samples[i]
        end
      end

      chart_data.append({
        time: timestamp.strftime("%H:%M:%S"),
        heart_rate: heart_rate,
        distance: distance,
        pace: pace
      })

      #r = []
      #r << timestamp.strftime("%H:%M:%S")
      #r << "#{"%7.1f" % samples.distance_samples[i]} m" if samples.distance_samples[i]
      #r << "#{"%3.2f" % (60.0 / samples.speed_samples[i])} min/km" if samples.speed_samples[i]
      #r << "HR=#{"%3.0f" % samples.heart_rate_samples[i]} bpm" if samples.heart_rate_samples[i]
      #r << "alt=#{"%4.1f" % samples.altitude_samples[i]}#{" (corrected=#{"%4.1f" % (samples.altitude_samples[i] + altitude_delta)})" if altitude_delta != 0} m" if samples.altitude_samples[i]
      #r << "temp=#{"%2.1f" % samples.temperature_samples[i]} °C" if samples.temperature_samples[i]
      #r << "cadence=#{samples.cadence_samples[i]}" if samples.cadence_samples[i]
      #r << "stride length=#{samples.stride_length_samples[i]}" if samples.stride_length_samples[i]
      #r << "left power=#{samples.left_pedal_power_samples[i].current_power}" if samples.left_pedal_power_samples[i]
      #r << "right power=#{samples.right_pedal_power_samples[i].current_power}" if samples.right_pedal_power_samples[i]
      #r << "forward acceleration=#{samples.forward_acceleration[i]}" if samples.forward_acceleration[i]
      #r << "moving type=#{samples.moving_type_samples[i]}" if samples.moving_type_samples[i]
    end

    gps_track_positions = Array.new

    route_samples_count = @route_samples.latitude.count
    if route_samples_count > 0
      for i in 0..route_samples_count-1
        gps_track_positions.append([
          @route_samples.latitude[i],
          @route_samples.longitude[i]
        ])
      end
    end

    @chart_data = chart_data
    @gps_track_positions = gps_track_positions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/training_helper.rb
module TrainingHelper
end

app/views/calendar/index.html.erb
<h1>Calendar</h1>

<%= javascript_pack_tag 'calendar' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolarViewer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/training/details.html.erb
<%= link_to 'Back', training_times_path(@date) %>

<% if @sport %>
  <h1>Training#details</h1>

  <p><%= @sport.translation.map { |t| t.text.text if t.id.language == 'en' }.compact.join('/') %></p>
  <p><%= pb_sysdatetime_to_string @training_session.start, @training_session.start.time_zone_offset %></p>
  <p><%= pb_sysdatetime_to_string @training_session.end, @training_session.end.time_zone_offset %></p>
  <p><%= pb_duration_to_string @training_session.duration %></p>

  <h2>Heart rate</h2>
  <% if @exercise_stats.heart_rate %>
    <p>
    &Oslash; <%= @exercise_stats.heart_rate.average %>;
    max <%= @exercise_stats.heart_rate.maximum %>
    </p>
  <% end %>
  <canvas id="heart_rate_chart" width="800" height="300"></canvas>

  <h2>Pace</h2>
  <% if @exercise_stats.speed %>
    <p>
    &Oslash; <%= "%3.2f" % @exercise_stats.speed.average %> km/h;
    max <%= "%3.2f" % @exercise_stats.speed.maximum %> km/h
    </p>
  <% end %>
  <canvas id="pace_chart" width="800" height="300"></canvas>

  <h2>Distance</h2>
  <p>total <%= "%.1f" % @training_session.distance %>m</p>
  <canvas id="distance_chart" width="800" height="300"></canvas>
  <div id="map" style="width: 600px; height: 600px;"></div>

  <%= javascript_pack_tag "training" %>

  <script type="text/javascript">
    var chartData = <%= @chart_data.to_json.html_safe %>;
    var gpsTrackPositions = <%= @gps_track_positions.to_json.html_safe %>;

    const labels = [];
    const heartRateData = [];
    const paceData = [];
    const distanceData = [];
    for (const data of chartData) {
          labels.push(data.time);
          heartRateData.push(data.heart_rate);
          paceData.push(data.pace);
          distanceData.push(data.distance);
        }

    drawChart('heart_rate_chart', 'Heart rate', labels, heartRateData, 'red');
    drawChart('pace_chart', 'Distance', labels, paceData, 'green');
    drawChart('distance_chart', 'Distance', labels, distanceData, 'blue');

    if (gpsTrackPositions.length > 0) {
          var myIcon = L.icon({
            iconUrl: '<%= image_path "marker-icon.png" %>',
            iconSize: [25, 41],
            iconAnchor: [12, 41],
            shadowUrl: '<%= image_path "marker-shadow.png" %>',
            shadowSize: [41, 41],
            shadowAnchor: [12, 41]
          });
          const map = L.map('map');
          const tileLayer = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
          });
          tileLayer.addTo(map);

          const gpsTrack = L.polyline(gpsTrackPositions, {
            color: 'red',
          });
          let marker = L.marker([0, 0], {icon: myIcon});
          gpsTrack.on('mouseover', e => {
            marker.setLatLng(e.latlng);
            if (!map.hasLayer(marker)) {
              marker.addTo(map);
            }
          });
          gpsTrack.on('mouseout', e => {
            marker.removeFrom(map);
          });
          gpsTrack.addTo(map);
          map.fitBounds(gpsTrack.getBounds());
        }
  </script>
<% else %>
  <p>No exercise found</p>
<% end %>

app/views/training/list_dates.html.erb
<% if @dates %>
  <ul>
    <% @dates.each do |date| %>
      <li>
        <%= link_to date, training_times_path(date) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No dates found</p>
<% end %>

app/views/training/list_times.html.erb
<%= link_to 'Back', training_dates_path() %>

<% if @times %>
  <ul>
    <% @times.each do |time| %>
      <li>
        <%= link_to time, training_details_path(@date, time) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No exercises found</p>
<% end %>